name: Rebuild base16 colorschemes
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # https://crontab.guru/every-day
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Build
        run: nix-shell --run "mmake"
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update repository with the latest base16 colorschemes
          branch: ${{ github.head_ref }}
