name: Update the repository with the latest base16 colorschemes
on:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          args: install
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Run make
        run: poetry run make
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update repository with the latest base16 colorschemes
          branch: ${{ github.head_ref }}
